# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67b736dbf814885de07db8c0d6a6e7fde6121f67b7236d3164868bdec91267ab9e98a2eccf4573b94eaefe63ff2178f0dd50922fbd0df0e65b76c338ac663d5b

test:
  secret_key_base: a805c5139219a7a4d2aa9014f9c7d87e20492b9c91b8ee8ab31ebf6130c36bed510bec6cb382d231d1df762cecf69996a09bd79eb5bca358f5c8b8718b625b7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
